---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: codgen-0624
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codgen-0624 
  name: codgen-0624
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi